# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: '/img'
collections:
  - name: 'modules'
    label: 'Modules'
    folder: 'modules/content/_posts/'
    fields:
      - {label: "Title", name: "title", widget: "string"}